pipeline {
	agent any
	stages {

		stage('Create Kubernetes Cluster') {
			steps {
				withAWS(region:'us-east-1', credentials:'aws_credentials') {
					sh '''
						eksctl create cluster \
						--name udacitycluster \
						--version 1.23 \
						--node-type t2.small \
						--nodes 2 \
						--nodes-min 1 \
						--nodes-max 2 \
						--region us-east-1 \
						--zones us-east-1a \
						--zones us-east-1b
					'''
				}
			}
		}

		stage('Configure kubectl') {
			steps {
				withAWS(region:'us-east-1', credentials:'aws_credentials') {
					sh '''
						aws eks --region us-east-1 update-kubeconfig --name udacitycluster
					'''
				}
			}
		}

	}
}
